language: node_js
node_js:
  - "10"
deploy:
  provider: script
  skip_cleanup: true
  script: chmod a+x ./bash_scripts/deploy_master.sh && ./bash_scripts/deploy_master.sh && rvm use 2.7.8 do script.rb
script: ./bash_scripts/deploy.sh
